name: Welcome To Planet Earth
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52698
title: Welcome To Planet Earth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#021841'
    - '#687ac8'
    - '#b9c1e9'
    - '#f7fcfe'
    - '#bcefff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
