name: Welcome To Planet Earth
favicon: null
layout_spectrum: 0.5829787
typography_spectrum: 0.67034
title: Welcome To Planet Earth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#feffed'
    - '#053075'
    - '#bbd0d1'
    - '#325f86'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
